version: '3.7' # Docker Composeの安定版を使用

# --------------------------
# サービス定義 (コンテナ)
# --------------------------
services:
  # 1. MariaDB データベースコンテナ
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_data: /var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
    restart: unless-stopped


  # 2. WordPress + PHP-FPM コンテナ
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_data: /var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: unless-stopped

  # 3. NGINX リバースプロキシコンテナ
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      wordpress_volume: /var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: unless-stopped

# --------------------------
# ネットワーク定義
# --------------------------
networks:
  # コンテナ間の接続のためのカスタムブリッジネットワークを定義 [cite: 91, 100]
  inception_network:
    driver: bridge # 依存関係: 'network: host' や '--link' は禁止されています [cite: 99]

# --------------------------
# ボリューム定義 (永続化データ)
# --------------------------
volumes:
  # MariaDBのデータ専用ボリューム
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      # ホストの /home/login/data/mariadb ディレクトリをバインド
      device: /home/${LOGIN}/data/mariadb
      o: bind

  # WordPressのデータ専用ボリューム
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      # ホストの /home/login/data/wordpress ディレクトリをバインド
      device: /home/${LOGIN}/data/wordpress
      o: bind